name = "BonitoMLTools"
uuid = "d95ba484-c33a-4ae3-8213-8869eb3ef5bb"
authors = ["Simon Danisch"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
